#ifndef __CPUTYPE_H__
#define __CPUTYPE_H__
#define ARM_CPU_IMP_ARM			    0x41
#define ARM_CPU_IMP_APM			    0x50
#define ARM_CPU_IMP_CAVIUM		    0x43
#define ARM_CPU_IMP_BRCM		    0x42
#define ARM_CPU_IMP_QCOM		    0x51
#define ARM_CPU_IMP_NVIDIA		    0x4E
#define ARM_CPU_IMP_FUJITSU		    0x46
#define ARM_CPU_IMP_HISI		    0x48
#define ARM_CPU_IMP_APPLE		    0x61
#define ARM_CPU_IMP_AMPERE		    0xC0

static const char *const CPU_IMPLEMENTER[] = {
	[ARM_CPU_IMP_ARM]		= "ARM",
	[ARM_CPU_IMP_APM]		= "APM",
	[ARM_CPU_IMP_CAVIUM]    = "CAVIUM",
	[ARM_CPU_IMP_BRCM]		= "BRCM",
	[ARM_CPU_IMP_QCOM]		= "QCOM",
	[ARM_CPU_IMP_NVIDIA]	= "NVIDIA",
	[ARM_CPU_IMP_FUJITSU]	= "FUJITSU",
	[ARM_CPU_IMP_HISI]		= "HISI",
	[ARM_CPU_IMP_APPLE]		= "APPLE",
	[ARM_CPU_IMP_AMPERE]	= "AMPERE"
};


#define ARM_CPU_PART_CORTEX_A57		0xD07
#define ARM_CPU_PART_CORTEX_A72		0xD08
#define ARM_CPU_PART_CORTEX_A53		0xD03
#define ARM_CPU_PART_CORTEX_A73		0xD09
#define ARM_CPU_PART_CORTEX_A75		0xD0A
#define ARM_CPU_PART_CORTEX_A55		0xD05
#define ARM_CPU_PART_CORTEX_A76		0xD0B
#define ARM_CPU_PART_CORTEX_A77		0xD0D
#define ARM_CPU_PART_CORTEX_A78		0xD41
#define ARM_CPU_PART_CORTEX_A78AE	0xD42
static const char *const CPU_PART[] = {
    [ARM_CPU_PART_CORTEX_A57] = "A57",
    [ARM_CPU_PART_CORTEX_A72] = "A72",
    [ARM_CPU_PART_CORTEX_A53] = "A53",
    [ARM_CPU_PART_CORTEX_A73] = "A73",
    [ARM_CPU_PART_CORTEX_A75] = "A75",
    [ARM_CPU_PART_CORTEX_A55] = "A55",
    [ARM_CPU_PART_CORTEX_A76] = "A76",
    [ARM_CPU_PART_CORTEX_A77] = "A77",
    [ARM_CPU_PART_CORTEX_A78] = "A78",
    [ARM_CPU_PART_CORTEX_A78AE] = "A78AE"
};



#endif //__CPUTYPE_H__